release:
    mkdir -p release
    cp latex/build/hw8.pdf release/hw8.pdf
    cp src/hw8.py release/
    cp src/question1.py release/
    cd release && zip hw8.zip ./*
    mv release/hw8.zip ~/Downloads
    rm -rf release
    echo "Released hw8.zip (~/Downloads/hw8.zip)."

clean:
    lmkw clean
